# Generated by Django 5.2.5 on 2025-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets_available',
            field=models.PositiveIntegerField(default=100, verbose_name='Доступно билетов'),
        ),
    ]
