# Generated by Django 5.2.5 on 2025-09-27 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_is_free_event_tickets_available_cart_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-registration_date', '-created_at'], 'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранные мероприятия'},
        ),
        migrations.AddField(
            model_name='event',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Для начинающих'), ('intermediate', 'Средний уровень'), ('advanced', 'Для продвинутых'), ('all', 'Для всех уровней')], default='all', max_length=20, verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('hybrid', 'Гибридный')], default='offline', max_length=10, verbose_name='Формат проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='requirements',
            field=models.TextField(blank=True, verbose_name='Что нужно взять с собой'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('education', 'Образовательные'), ('business', 'Бизнес'), ('entertainment', 'Развлечения'), ('culture', 'Культура'), ('sport', 'Спорт'), ('social', 'Социальные')], default='education', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('webinar', 'Вебинар'), ('workshop', 'Мастер-класс'), ('course', 'Курс'), ('lecture', 'Лекция'), ('training', 'Тренинг'), ('conference', 'Конференция'), ('business_meeting', 'Бизнес-встреча'), ('networking', 'Нетворкинг'), ('exhibition', 'Выставка'), ('concert', 'Концерт'), ('party', 'Вечеринка'), ('festival', 'Фестиваль'), ('show', 'Шоу'), ('exhibition_culture', 'Выставка (культурная)'), ('tour', 'Экскурсия'), ('master_class', 'Мастер-класс (творческий)'), ('competition', 'Соревнование'), ('sport_event', 'Спортивное событие'), ('tournament', 'Турнир'), ('charity', 'Благотворительное'), ('volunteering', 'Волонтерство'), ('community', 'Сообщество')], default='workshop', max_length=20, verbose_name='Тип мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, to='events.tag', verbose_name='Теги'),
        ),
    ]
