# Generated by Django 5.2.5 on 2025-09-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
        ('events', '0002_sample_events'),
    ]

    operations = [
    ]
