# Generated by Django 5.2.5 on 2025-09-07 19:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_tickets_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='video_ads/')),
                ('thumbnail', models.ImageField(upload_to='video_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='is_background_video',
            field=models.BooleanField(default=False, verbose_name='Использовать как фоновое видео'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Превью видео'),
        ),
        migrations.AddField(
            model_name='event',
            name='video_trailer',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'])], verbose_name='Видео-трейлер'),
        ),
    ]