# Generated by Django 5.2.5 on 2025-09-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_created_at_alter_event_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('ad_type', models.CharField(choices=[('banner', 'Баннер'), ('video', 'Видео'), ('popup', 'Всплывающее окно'), ('sidebar', 'Боковая панель')], default='banner', max_length=20, verbose_name='Тип рекламы')),
                ('position', models.CharField(choices=[('top', 'Верх страницы'), ('sidebar', 'Боковая панель'), ('between_events', 'Между событиями'), ('bottom', 'Низ страницы')], default='top', max_length=20, verbose_name='Позиция')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='Изображение')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Текстовое содержание')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('click_count', models.IntegerField(default=0, verbose_name='Клики')),
                ('impression_count', models.IntegerField(default=0, verbose_name='Показы')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
                'ordering': ['-start_date'],
            },
        ),
    ]
