# Generated by Django 5.2.5 on 2025-10-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_category_options_registration_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEventSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название источника')),
                ('url', models.URLField(verbose_name='URL источника')),
                ('parser_config', models.JSONField(default=dict, verbose_name='Конфигурация парсера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
            ],
            options={
                'verbose_name': 'Источник мероприятий',
                'verbose_name_plural': 'Источники мероприятий',
            },
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатное')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('external_url', models.URLField(verbose_name='URL на внешнем сайте')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Сырые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.externaleventsource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Внешнее мероприятие',
                'verbose_name_plural': 'Внешние мероприятия',
                'ordering': ['-date'],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
