# Generated by Django 5.2.5 on 2025-10-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_externaleventsource_externalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(default='education', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category', verbose_name='Категория'),
        ),
    ]
