# Generated by Django 5.2.5 on 2025-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badges',
            field=models.JSONField(blank=True, default=list, verbose_name='Бейджи'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('webinar', 'Вебинар'), ('workshop', 'Мастер-класс'), ('course', 'Курс'), ('lecture', 'Лекция'), ('training', 'Тренинг'), ('conference', 'Конференция'), ('business_meeting', 'Бизнес-встреча'), ('networking', 'Нетворкинг'), ('exhibition', 'Выставка'), ('concert', 'Концерт'), ('party', 'Вечеринка'), ('festival', 'Фестиваль'), ('show', 'Шоу'), ('exhibition_culture', 'Выставка (культурная)'), ('tour', 'Экскурсия'), ('master_class', 'Мастер-класс (творческий)'), ('competition', 'Соревнование'), ('sport_event', 'Спортивное событие'), ('tournament', 'Турнир'), ('charity', 'Благотворительное'), ('volunteering', 'Волонтерство'), ('community', 'Сообщество'), ('trending', '🔥 Популярное'), ('new', '🆕 Новое'), ('featured', '⭐ Рекомендуемое'), ('early_bird', '🐦 Ранняя пташка'), ('last_chance', '⏰ Последний шанс'), ('sold_out', '🔴 Продано'), ('exclusive', '👑 Эксклюзив'), ('discount', '💸 Скидка')], default='workshop', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
