# Generated by Django 5.2.5 on 2025-10-07 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_latitude_event_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuddyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('individual', 'Индивидуальный попутчик'), ('group', 'Группа'), ('any', 'Любой вариант')], max_length=20, verbose_name='Тип запроса')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('max_group_size', models.PositiveIntegerField(default=1, verbose_name='Максимальный размер группы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос попутчика',
                'verbose_name_plural': 'Запросы попутчиков',
            },
        ),
        migrations.CreateModel(
            name='TravelBuddyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название группы')),
                ('description', models.TextField(verbose_name='Описание группы')),
                ('max_members', models.PositiveIntegerField(default=10, verbose_name='Максимальное количество участников')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная группа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_groups', to='events.event')),
            ],
            options={
                'verbose_name': 'Группа попутчиков',
                'verbose_name_plural': 'Группы попутчиков',
            },
        ),
        migrations.CreateModel(
            name='TravelBuddyMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_message', models.BooleanField(default=False, verbose_name='Системное сообщение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.travelbuddygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение группы',
                'verbose_name_plural': 'Сообщения групп',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelBuddyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, verbose_name='Утвержден')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='events.travelbuddygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник группы',
                'verbose_name_plural': 'Участники групп',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
