# Generated by Django 5.2.5 on 2025-10-16 21:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_achievement_chatentity_chatintent_levelsystem_quest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPromoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ролика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_type', models.CharField(choices=[('main', 'Главный проморолик'), ('demo', 'Демо-ролик'), ('tutorial', 'Обзорный туториал'), ('testimonial', 'Отзывы пользователей')], default='main', max_length=15, verbose_name='Тип ролика')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='project_promo/thumbnails/', verbose_name='Превью')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('show_on_homepage', models.BooleanField(default=True, verbose_name='Показывать на главной')),
                ('show_on_landing', models.BooleanField(default=True, verbose_name='Показывать в лендинге')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Автовоспроизведение')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='Клики')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/project_promo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Видео файл')),
            ],
            options={
                'verbose_name': 'Проморолик проекта',
                'verbose_name_plural': 'Проморолики проекта',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='events/', validators=[events.models.validate_image]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=300, verbose_name='Место проведения'),
        ),
        migrations.CreateModel(
            name='PromoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ролика')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video_source', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('upload', 'Загруженное видео'), ('external', 'Внешняя ссылка')], default='youtube', max_length=10, verbose_name='Источник видео')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('vimeo_url', models.URLField(blank=True, verbose_name='Vimeo URL')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='promo_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'webm'])], verbose_name='Загруженное видео')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/', verbose_name='Превью видео')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Длительность')),
                ('is_main_promo', models.BooleanField(default=False, verbose_name='Главное промо')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('autoplay', models.BooleanField(default=False, verbose_name='Автовоспроизведение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_videos', to='events.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Промо-видео',
                'verbose_name_plural': 'Промо-видео',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
