# Generated by Django 5.2.5 on 2025-10-10 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('patterns', models.JSONField(default=list, help_text='Список паттернов для интента')),
                ('responses', models.JSONField(default=list, help_text='Список ответов бота')),
                ('action', models.CharField(blank=True, help_text='Действие для выполнения', max_length=100)),
                ('required_entities', models.JSONField(default=list, help_text='Обязательные сущности')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Интент чатбота',
                'verbose_name_plural': 'Интенты чатбота',
            },
        ),
        migrations.CreateModel(
            name='ChatEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('patterns', models.JSONField(default=list, help_text='Паттерны для извлечения сущности')),
                ('entity_type', models.CharField(choices=[('category', 'Категория'), ('date', 'Дата'), ('price', 'Цена'), ('location', 'Местоположение'), ('event_type', 'Тип мероприятия')], max_length=50)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='chatbot.chatintent')),
            ],
            options={
                'verbose_name': 'Сущность чатбота',
                'verbose_name_plural': 'Сущности чатбота',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чатов',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'ordering': ['created_at'],
            },
        ),
    ]